using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using XddbBuilder;

if (args.Length != 1)
{
    Console.Error.WriteLine("usage: XddbBuilder <input>");
    return 1;
}

var inputPath = args[0];
var baseDir = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", ".."));
var csOutputPath = Path.Combine(baseDir, "PokemonXDRNGLibrary.XDDB", "XDDBIndex.cs");
var seedsOutputPath = Path.Combine(baseDir, "PokemonXDRNGLibrary.XDDB.Data", "Resources", "seeds.bin");

// 旧形式のXDDBは(hpcode,seed)のペアがすべて列挙されたバイナリなので、これをベースに変換する
var data = File.ReadAllBytes(inputPath);
int nRec = data.Length / 8;

var groups = new Dictionary<uint, List<uint>>();
for (int i = 0; i < nRec; i++)
{
    uint hp = BitConverter.ToUInt32(data, i * 8);
    uint seed = BitConverter.ToUInt32(data, i * 8 + 4);
    if (!groups.TryGetValue(hp, out var list)) { list = new List<uint>(); groups[hp] = list; }
    list.Add(seed);
}

var codes = groups.Keys.ToArray();
Array.Sort(codes);
int n = codes.Length;
foreach (var c in codes) groups[c].Sort();

var result = RecSplitMphBuilder.Build(codes);

var seen = new bool[n];
foreach (var c in codes)
{
    int slot = RecSplitMphBuilder.Lookup(result, c);
    if (slot < 0 || slot >= n) { Console.Error.WriteLine($"slot out of range: {slot}"); return 2; }
    if (seen[slot]) { Console.Error.WriteLine($"slot collision at {slot}"); return 2; }
    seen[slot] = true;
}

var seeds = new uint[n];
var overflow = new List<(uint slot, uint seed)>();
foreach (var c in codes)
{
    int slot = RecSplitMphBuilder.Lookup(result, c);
    var list = groups[c];
    seeds[slot] = list[0];
    for (int i = 1; i < list.Count; i++) overflow.Add(((uint)slot, list[i]));
}
overflow.Sort((a, b) => a.slot.CompareTo(b.slot));

// seeds.bin
using (var fs = File.Create(seedsOutputPath))
{
    for (int i = 0; i < n; i++)
    {
        var s = seeds[i];
        fs.WriteByte((byte)(s & 0xFF));
        fs.WriteByte((byte)((s >> 8) & 0xFF));
        fs.WriteByte((byte)((s >> 16) & 0xFF));
    }
}

// XDDBIndex.cs
using (var sw = new StreamWriter(csOutputPath, false, new UTF8Encoding(false)))
{
    sw.WriteLine("// <auto-generated/>");
    sw.WriteLine();
    sw.WriteLine("using System;");
    sw.WriteLine("using System.Collections.Generic;");
    sw.WriteLine();
    sw.WriteLine("namespace PokemonXDRNGLibrary.XDDB");
    sw.WriteLine("{");

    // データ
    sw.WriteLine("    internal static class XDDBIndex");
    sw.WriteLine("    {");
    sw.WriteLine($"        internal const int N = {result.N};");
    sw.WriteLine();

    sw.Write("        internal static readonly int[] BucketSize = new int[] { ");
    sw.Write(string.Join(", ", result.BucketSize));
    sw.WriteLine(" };");
    sw.WriteLine();

    sw.Write("        internal static readonly long[] BitOffset = new long[] { ");
    sw.Write(string.Join(", ", result.BitOffset));
    sw.WriteLine(" };");
    sw.WriteLine();

    sw.WriteLine($"        internal static readonly byte[] Bits = new byte[{result.Bits.Length}]");
    sw.WriteLine("        {");
    for (int i = 0; i < result.Bits.Length; i += 32)
    {
        sw.Write("            ");
        int end = Math.Min(i + 32, result.Bits.Length);
        for (int j = i; j < end; j++)
        {
            sw.Write($"0x{result.Bits[j]:X2}");
            if (j < result.Bits.Length - 1) sw.Write(", ");
        }
        sw.WriteLine();
    }
    sw.WriteLine("        };");
    sw.WriteLine();

    sw.Write("        internal static readonly uint[] OverflowSlots = new uint[] { ");
    sw.Write(string.Join(", ", overflow.Select(o => o.slot)));
    sw.WriteLine(" };");
    sw.WriteLine();

    sw.Write("        internal static readonly uint[] OverflowSeeds = new uint[] { ");
    sw.Write(string.Join(", ", overflow.Select(o => o.seed)));
    sw.WriteLine(" };");

    sw.WriteLine("    }");
    sw.WriteLine();

    // RecSplitMph の共有コード
    sw.Write(RecSplitMphBuilder.GenerateSharedSource());

    sw.WriteLine("}");
}

return 0;
